import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

Color kMainColor = Color(0xff002e2b);
Color kDisabledColor = Color(0xff616161);
Color kTextColor = Color(0xfffff9e9);
Color kWhiteColor = Colors.white;
Color kLightTextColor = Color(0xff747474);
Color kCardBackgroundColor = Color(0xfff8f9fd);
Color kTransparentColor = Colors.transparent;
Color kMainTextColor = Color(0xff000000);
Color kIconColor = Color(0xffc4c8c1);
Color kHintColor = Color(0xffa3a3a3);
Color kNavigationButtonColor = Color(0xffd09b1a);
Color kContainerTextColor = Color(0xff606060);
Color kButtonColor = Color(0xfffafafa);
Color kButtonBorderColor = Color(0xffe1e1e1);
Color kButtonTextColor = Color(0xffbababa);
Color kContainerShadowColor = Color(0xff87fddc82);
Color kRedColor = Color(0xffdc143c);
